#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Simple Bot to reply to Telegram messages.

This is built on the API wrapper, see echobot2.py to see the same example built
on the telegram.ext bot framework.
This program is dedicated to the public domain under the CC0 license.
"""
import logging
import telegram
from telegram.error import NetworkError, Unauthorized
from time import sleep


update_id = None

def main():

    """Run the bot."""
    global update_id

    # Telegram Bot Authorization Token
    bot = telegram.Bot('529596097:AAGgh14YsUSwBKEb4QfHJmSnhHn47_4IrHU')

    # get the first pending update_id, this is so we can skip over it in case
    # we get an "Unauthorized" exception.
    try:
        update_id = bot.get_updates()[0].update_id
        print(bot.get_updates()[0].update_id)
    except IndexError:
        update_id = None

    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    while True:
        try:
            echo(bot)
        except NetworkError:
            sleep(1)
        except Unauthorized:
            # The user has removed or blocked the bot.
            update_id += 1


def echo(bot):
    """Echo the message the user sent."""
    global update_id
    # Request updates after the last update_id
    for update in bot.get_updates(offset=update_id, timeout=1):
        update_id = update.update_id + 1

        if update.message.text=="미세먼지":
            # your bot can receive updates without messages
            # Reply to the message
            #update.message.reply_text(update.message.text)
            print(update.message)
            update.message.reply_text("안녕하세요! 저는 논현초 미세먼지 봇입니다^^\n현재 논현초등학교의 미세먼지 농도는 GOOOOOD입니다.^^")


if __name__ == '__main__':
    main()